# Cloudflare Pages Configuration (NOT Workers)
name = "ghost-automation-dashboard-three"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

# NO WORKERS - Pages only
# Build configuration is handled by Cloudflare Pages dashboard