import { NextRequest, NextResponse } from 'next/server'

export async function GET(
  request: NextRequest,
  { params }: { params: { filename: string } }
) {
  try {
    const { filename } = params
    
    // For now, create a mock video file with content
    const mockVideoContent = `# Generated Video: ${filename}

## Instructions for Video Creation:
1. Use the generated script as your narration
2. Record video with quick cuts every 2-3 seconds
3. Add trending audio in the background
4. Use vertical 9:16 aspect ratio for TikTok
5. Include visual elements that match the content type

## Video Specifications:
- Duration: 30-60 seconds
- Format: MP4
- Resolution: 1080x1920 (vertical)
- Frame Rate: 30fps

## Generated by:
Ghost Automation Dashboard
Video Generation System

Note: This is a placeholder file. In production, this would be the actual video file.
`

    // Create a response with the mock content as a downloadable file
    const response = new NextResponse(mockVideoContent)
    
    response.headers.set('Content-Type', 'text/plain')
    response.headers.set('Content-Disposition', `attachment; filename="${filename.replace('.mp4', '.txt')}"`)
    
    return response
    
  } catch (error) {
    console.error('Video download error:', error)
    return NextResponse.json(
      { error: 'Failed to download video' },
      { status: 500 }
    )
  }
}