name = "ghost-automation-api-images"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

[[routes]]
pattern = "*/api/generate-images"